### ISSUE TITLE
Multi CPUs parallel execution 

### ISSUE THREAD

**Issue by matbord** [signetlabdei/sem#45]
Hi,
where can I find an example of how to run my NS3 simulations in parallel with SEM using all my CPUs?
I'm actually using `campaign.run_missing_simulations(params, runs=runs)`

**Comment by DvdMgr** [comment]
By default, all available CPUs are used. If you want to reduce this number (so that you have some free resources to run other programs, for instance), you can pass the `max_parallel_processes` argument when you create the `CampaignManager` object, specifying how many simulations should be launched in parallel (assuming you are using the current `develop` branch). I have updated the [WiFi Plots example](https://github.com/signetlabdei/sem/blob/bdccf5bcd5d4f3d1d6ea3b46b31000ec491a857c/examples/WiFi%20Plots.ipynb) with this parameter.
